### Type definitions saved at 2019-09-07T16:48:13.878Z ###

type ImageSharp implements Node @childOf(mimeTypes: [], types: ["File"], many: false) @dontInfer

type MarkdownHeading {
  value: String
  depth: Int
}

enum MarkdownHeadingLevels {
  h1
  h2
  h3
  h4
  h5
  h6
}

enum MarkdownExcerptFormats {
  PLAIN
  HTML
  MARKDOWN
}

type MarkdownWordCount {
  paragraphs: Int
  sentences: Int
  words: Int
}

type MarkdownRemark implements Node @childOf(mimeTypes: ["text/markdown", "text/x-markdown"], types: [], many: false) @dontInfer {
  frontmatter: MarkdownRemarkFrontmatter
  excerpt: String
  rawMarkdownBody: String
}

type MarkdownRemarkFrontmatter {
  title: String
}

type ContentfulContentType implements Node @dontInfer {
  name: String
  displayField: String
  description: String
}

type ContentfulCollectionItem implements Node @dontInfer {
  name: String
  type: String
  datePublished: Date @dateformat
  dateLastEdit: Date @dateformat
  author: String
  categories: [String]
  featuredImage: ContentfulAsset @link(by: "id", from: "featuredImage___NODE")
  gallery: [ContentfulAsset] @link(by: "id", from: "gallery___NODE")
  scripts: [ContentfulScript] @link(by: "id", from: "scripts___NODE")
  block___references: [ContentfulBlockReferences] @link(by: "id", from: "block - references___NODE") @proxy(from: "block - references___NODE")
  content: contentfulCollectionItemContentTextNode @link(by: "id", from: "content___NODE")
  metadata: contentfulCollectionItemMetadataJsonNode @link(by: "id", from: "metadata___NODE")
  options: contentfulCollectionItemOptionsJsonNode @link(by: "id", from: "options___NODE")
  style: contentfulCollectionItemStyleJsonNode @link(by: "id", from: "style___NODE")
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  node_locale: String
}

type ContentfulAsset implements Node @dontInfer {
  contentful_id: String
  file: ContentfulAssetFile
  title: String
  description: String
  node_locale: String
}

type ContentfulAssetFile {
  url: String
  details: ContentfulAssetFileDetails
  fileName: String
  contentType: String
}

type ContentfulAssetFileDetails {
  size: Int
  image: ContentfulAssetFileDetailsImage
}

type ContentfulAssetFileDetailsImage {
  width: Int
  height: Int
}

type ContentfulScript implements Node @dontInfer {
  name: String
  src: String
  type: String
  charset: String
  collection_item: [ContentfulCollectionItem] @link(by: "id", from: "collection item___NODE") @proxy(from: "collection item___NODE")
  settings: [ContentfulSettings] @link(by: "id", from: "settings___NODE")
  page: [ContentfulPage] @link(by: "id", from: "page___NODE")
  content: contentfulScriptContentTextNode @link(by: "id", from: "content___NODE")
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  node_locale: String
}

type ContentfulSettings implements Node @dontInfer {
  name: String
  menu: [ContentfulPage] @link(by: "id", from: "menu___NODE")
  favicon: ContentfulAsset @link(by: "id", from: "favicon___NODE")
  facebookImage: ContentfulAsset @link(by: "id", from: "facebookImage___NODE")
  scripts: [ContentfulScript] @link(by: "id", from: "scripts___NODE")
  metadata: contentfulSettingsMetadataJsonNode @link(by: "id", from: "metadata___NODE")
  colors: contentfulSettingsColorsJsonNode @link(by: "id", from: "colors___NODE")
  fonts: contentfulSettingsFontsJsonNode @link(by: "id", from: "fonts___NODE")
  contact: contentfulSettingsContactJsonNode @link(by: "id", from: "contact___NODE")
  options: contentfulSettingsOptionsJsonNode @link(by: "id", from: "options___NODE")
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  node_locale: String
}

type ContentfulPage implements Node @dontInfer {
  path: String
  blocks: [ContentfulBlockFormContentfulBlockFreeTextContentfulBlockGalleryContentfulBlockReferencesContentfulSectionUnion] @link(by: "id", from: "blocks___NODE")
  scripts: [ContentfulScript] @link(by: "id", from: "scripts___NODE")
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  node_locale: String
  block___references: [ContentfulBlockReferences] @link(by: "id", from: "block - references___NODE") @proxy(from: "block - references___NODE")
  settings: [ContentfulSettings] @link(by: "id", from: "settings___NODE")
  metadata: contentfulPageMetadataJsonNode @link(by: "id", from: "metadata___NODE")
}

union ContentfulBlockFormContentfulBlockFreeTextContentfulBlockGalleryContentfulBlockReferencesContentfulSectionUnion = ContentfulBlockForm | ContentfulBlockFreeText | ContentfulBlockGallery | ContentfulBlockReferences | ContentfulSection

type ContentfulBlockReferences implements Node @dontInfer {
  name: String
  references: [ContentfulCollectionItemContentfulPageUnion] @link(by: "id", from: "references___NODE")
  section: [ContentfulSection] @link(by: "id", from: "section___NODE")
  page: [ContentfulPage] @link(by: "id", from: "page___NODE")
  options: contentfulBlockReferencesOptionsJsonNode @link(by: "id", from: "options___NODE")
  style: contentfulBlockReferencesStyleJsonNode @link(by: "id", from: "style___NODE")
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  node_locale: String
}

union ContentfulCollectionItemContentfulPageUnion = ContentfulCollectionItem | ContentfulPage

type ContentfulSection implements Node @dontInfer {
  name: String
  blocks: [ContentfulBlockFormContentfulBlockFreeTextContentfulBlockGalleryContentfulBlockReferencesUnion] @link(by: "id", from: "blocks___NODE")
  page: [ContentfulPage] @link(by: "id", from: "page___NODE")
  options: contentfulSectionOptionsJsonNode @link(by: "id", from: "options___NODE")
  style: contentfulSectionStyleJsonNode @link(by: "id", from: "style___NODE")
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  node_locale: String
}

union ContentfulBlockFormContentfulBlockFreeTextContentfulBlockGalleryContentfulBlockReferencesUnion = ContentfulBlockForm | ContentfulBlockFreeText | ContentfulBlockGallery | ContentfulBlockReferences

type contentfulSectionOptionsJsonNode implements Node @dontInfer

type contentfulSectionStyleJsonNode implements Node @dontInfer

type contentfulBlockReferencesOptionsJsonNode implements Node @dontInfer

type contentfulBlockReferencesStyleJsonNode implements Node @dontInfer

type contentfulPageMetadataJsonNode implements Node @dontInfer {
  name: String
  title: String
  description: String
}

type contentfulSettingsMetadataJsonNode implements Node @dontInfer {
  url: String
  name: String
  title: String
  description: String
}

type contentfulSettingsColorsJsonNode implements Node @dontInfer {
  palettes: [contentfulSettingsColorsJsonNodePalettes]
  mainCombo: String
  menuCombo: String
  footerCombo: String
}

type contentfulSettingsColorsJsonNodePalettes {
  name: String
  neutral: String
  primary: String
  secondary: String
}

type contentfulSettingsFontsJsonNode implements Node @dontInfer {
  body: [String]
  header: [String]
}

type contentfulSettingsContactJsonNode implements Node @dontInfer {
  name: String
  email: String
  phone: String
  facebook: String
  linkedin: String
  instagram: String
}

type contentfulSettingsOptionsJsonNode implements Node @dontInfer {
  typography: contentfulSettingsOptionsJsonNodeTypography
}

type contentfulSettingsOptionsJsonNodeTypography {
  scaleRatio: Int
  googleFonts: [contentfulSettingsOptionsJsonNodeTypographyGoogleFonts]
  baseFontSize: String
}

type contentfulSettingsOptionsJsonNodeTypographyGoogleFonts {
  name: String
  styles: [String]
}

type contentfulScriptContentTextNode implements Node @dontInfer {
  content: String
}

type contentfulCollectionItemContentTextNode implements Node @dontInfer {
  content: String
}

type contentfulCollectionItemMetadataJsonNode implements Node @dontInfer

type contentfulCollectionItemOptionsJsonNode implements Node @dontInfer

type contentfulCollectionItemStyleJsonNode implements Node @dontInfer

type ContentfulBlockForm implements Node @dontInfer {
  name: String
  section: [ContentfulSection] @link(by: "id", from: "section___NODE")
  page: [ContentfulPage] @link(by: "id", from: "page___NODE")
  form: contentfulBlockFormFormJsonNode @link(by: "id", from: "form___NODE")
  successMessage: contentfulBlockFormSuccessMessageTextNode @link(by: "id", from: "successMessage___NODE")
  errorMessage: contentfulBlockFormErrorMessageTextNode @link(by: "id", from: "errorMessage___NODE")
  options: contentfulBlockFormOptionsJsonNode @link(by: "id", from: "options___NODE")
  style: contentfulBlockFormStyleJsonNode @link(by: "id", from: "style___NODE")
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  node_locale: String
}

type contentfulBlockFormFormJsonNode implements Node @dontInfer

type contentfulBlockFormSuccessMessageTextNode implements Node @dontInfer {
  successMessage: String
}

type contentfulBlockFormErrorMessageTextNode implements Node @dontInfer {
  errorMessage: String
}

type contentfulBlockFormOptionsJsonNode implements Node @dontInfer

type contentfulBlockFormStyleJsonNode implements Node @dontInfer

type ContentfulBlockFreeText implements Node @dontInfer {
  name: String
  section: [ContentfulSection] @link(by: "id", from: "section___NODE")
  page: [ContentfulPage] @link(by: "id", from: "page___NODE")
  main: contentfulBlockFreeTextMainTextNode @link(by: "id", from: "main___NODE")
  options: contentfulBlockFreeTextOptionsJsonNode @link(by: "id", from: "options___NODE")
  style: contentfulBlockFreeTextStyleJsonNode @link(by: "id", from: "style___NODE")
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  node_locale: String
}

type contentfulBlockFreeTextMainTextNode implements Node @dontInfer {
  main: String
}

type contentfulBlockFreeTextOptionsJsonNode implements Node @dontInfer

type contentfulBlockFreeTextStyleJsonNode implements Node @dontInfer

type ContentfulBlockGallery implements Node @dontInfer {
  name: String
  gallery: [ContentfulAsset] @link(by: "id", from: "gallery___NODE")
  section: [ContentfulSection] @link(by: "id", from: "section___NODE")
  page: [ContentfulPage] @link(by: "id", from: "page___NODE")
  options: contentfulBlockGalleryOptionsJsonNode @link(by: "id", from: "options___NODE")
  style: contentfulBlockGalleryStyleJsonNode @link(by: "id", from: "style___NODE")
  contentful_id: String
  createdAt: Date @dateformat
  updatedAt: Date @dateformat
  node_locale: String
}

type contentfulBlockGalleryOptionsJsonNode implements Node @dontInfer

type contentfulBlockGalleryStyleJsonNode implements Node @dontInfer